name: Tag

on:
  workflow_dispatch:

permissions:
  contents: write


jobs:
  build:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@eef61447b9ff4aafe5dcd4e0bbf5d482be7e7871 # v4
        with:
          fetch-depth: 0

      - name: Retrieve current version number before release
        run: ./gradlew printVersion

      - name: Create release tag
        id: createRelease
        run: |
          ./gradlew releaseVersion --no-commit

      - name: Push new tag
        run: |
          git push origin --tags
